In [1]:
import numpy as np

In [7]:
a = np.array([1,2,3,4])
b = np.array([[1,3,2],[2,1,3]])

In [8]:
print(a.shape)
print(b.shape)

(4,)
(2, 3)


**gives the dimensions of our *a* array**

In [16]:
a.ndim

1

**this gives the dimensions of the array b**

In [15]:
b.ndim

2

specifying type in array (in this example do 16 bit integer (because values are small)

In [18]:
c = np.array([1,2,4], dtype='int16')

the following gives us the data type of the array

In [23]:
print(c.dtype)

int16


the following gives us the number of bytes

In [27]:
c.itemsize

2

In [28]:
a.itemsize

8

**practicing slicing and indexing:**

In [32]:
f = np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]], dtype ='int32')

if we want only the first row

In [33]:
f[0,:]

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)

for only the first column:

In [34]:
f[:,0]

array([1, 9], dtype=int32)

if we want the first 3 elements in all rows:

In [35]:
f[:,0:3]

array([[ 1,  2,  3],
       [ 9, 10, 11]], dtype=int32)

In [36]:
f[:,1:]

array([[ 2,  3,  4,  5,  6,  7,  8],
       [10, 11, 12, 13, 14, 15, 16]], dtype=int32)

In [38]:
f.shape

(2, 8)

**we can change the indexes**

In [39]:
f[1,1] = 99

In [40]:
print(f)

[[ 1  2  3  4  5  6  7  8]
 [ 9 99 11 12 13 14 15 16]]


In [41]:
f[:,:] = 1

In [42]:
print(f)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [43]:
f[:,3:] = [3,2,5,1,2]

In [44]:
print(f)

[[1 1 1 3 2 5 1 2]
 [1 1 1 3 2 5 1 2]]


for all zeros matrix:

In [45]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [47]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

**we are specifying the dimensions here**

In [49]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [50]:
np.ones((4,3,2)).shape

(4, 3, 2)

In [51]:
np.full((2,2), 98)

array([[98, 98],
       [98, 98]])

In [52]:
np.full((4,4,4), 1, dtype='int16')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [53]:
a = np.array([1,2,3])

In [54]:
np.full(a.shape,5)

array([5, 5, 5])

In [55]:
np.random.rand(4,2)

array([[0.9549209 , 0.95519481],
       [0.79870586, 0.34375813],
       [0.09418452, 0.09217502],
       [0.89667814, 0.10145671]])

In [56]:
np.random.rand(4,3,2)

array([[[0.86169034, 0.78845537],
        [0.14149583, 0.5204439 ],
        [0.47285621, 0.96716072]],

       [[0.79722133, 0.70369758],
        [0.03568894, 0.76596458],
        [0.61312166, 0.983001  ]],

       [[0.67755993, 0.071278  ],
        [0.80843102, 0.94187056],
        [0.85940815, 0.5474846 ]],

       [[0.86117075, 0.10991533],
        [0.83631137, 0.67308161],
        [0.09201468, 0.53490215]]])

**these are generating random numbers between zero and 1**

In [58]:
np.random.random_sample(a.shape)

array([0.26361497, 0.3306412 , 0.50953656])

In [61]:
np.random.randint(7)

5

In [62]:
np.random.randint(3,12)

6

In [63]:
np.random.randint(2,5, size = (4,2))

array([[4, 2],
       [2, 2],
       [4, 4],
       [2, 4]])

In [64]:
np.random.randint(-4,10, size = (3,4))

array([[ 1,  2,  8,  2],
       [-1,  0, -2,  3],
       [ 1,  4, -1,  2]])

In [70]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


**the axis in this case seems to represent what dimension of the array we are repeating**

In [71]:
r1 = np.repeat(arr, 4, axis = 1)

In [72]:
print(r1)

[[1 1 1 1 2 2 2 2 3 3 3 3]]


In [76]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [77]:
z.shape

(3, 3)

In [78]:
output.shape

(5, 5)

##### ***BE CAREFUL WHEN COPYING ARRAYS!***

In [79]:
a = np.array([2,32,123])
b = a

In [80]:
b[0] = 100
print(a)

[100  32 123]


This is similar to how lists work in python. our variables are pointing to the same array object, so to copy an array we can do a.copy

In [81]:
c = a.copy()

In [82]:
c[0] = 2222
print(a)
print(c)

[100  32 123]
[2222   32  123]


In [84]:
c = c*2
print(c)

[4444   64  246]


In [86]:
c = c/2
print(c)

[1111.    16.    61.5]


In [87]:
c = c**2
print(c)

[1.234321e+06 2.560000e+02 3.782250e+03]


In [88]:
k = np.cos(c)
print(k)

[-0.2396243  -0.03979076  0.97422091]


***LINEAR ALGEBRA***

In [98]:
a = np.ones((2,3))
b = np.full((3,2),2)
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


NOTICE THAT WE CAN MULTIPLY A AND B. we can multiply the columns of A by the rows of b to get a 2x2 matrix or a 3x3 matrix if we do a,b we are actually doing a on to b ie using a columns on to b rows, b,a is doing b columns on to a rows.

In [97]:
np.matmul(a,b)

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [99]:
np.matmul(b,a)

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

*** finding the determinant***
(we can also do things like eigen vectors etc.

In [100]:
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

***statistics***

In [101]:
a = np.array([3,3,34])

In [102]:
np.max(a)

np.int64(34)

In [106]:
k = np.array([3,4,5,2,3,34])
k

array([ 3,  4,  5,  2,  3, 34])

In [107]:
np.min(k)


np.int64(2)

In [108]:
np.mean(k)

np.float64(8.5)

In [110]:
np.sum(k)

np.int64(51)

***Reorganizing arrays***

In [111]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [112]:
after = before.reshape((8,1))

In [113]:
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [114]:
after = before.reshape((2,2,2))

In [115]:
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [121]:
# verticallly stacking vectors/matrices
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack((v1,v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [122]:
np.hstack((v1,v2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [123]:
# miscellaneous

In [124]:
#load file from data

In [125]:
# np.genfromtxt('data.txt', delimiter=','), this will return to use an arrrray of data split with the given delimeter. we can also make all in n array
#the same type ie:

In [128]:
v1 = v1.astype('float')
print(v1)
print(v1.dtype)

[1. 2. 3. 4.]
float64


***BOOL masking and advanced indexing***

In [ ]:
# we could do filedata > 50 and this will go through all the data and give true or false values for every thing.